// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Simple API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package main

import (
	"log"
	"net/http"

	"github.com/actualrockstar/simple-api-demo/go"
)

func main() {
	log.Printf("Server started")

	DefaultAPIService := simple_api.NewDefaultAPIService()
	DefaultAPIController := simple_api.NewDefaultAPIController(DefaultAPIService)

	router := simple_api.NewRouter(DefaultAPIController)

	log.Fatal(http.ListenAndServe(":80", router))
}
