// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Simple API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package simple_api

import (
	"context"
	"net/http"
	"errors"
	"fmt"
	
)

// DefaultAPIService is a service that implements the logic for the DefaultAPIServicer
// This service should implement the business logic for every endpoint for the DefaultAPI API.
// Include any external packages or services that will be required by this service.
type DefaultAPIService struct {
}

// NewDefaultAPIService creates a default api service
func NewDefaultAPIService() *DefaultAPIService {
	return &DefaultAPIService{}
}

// PostEcho - Echo back the message
func (s *DefaultAPIService) PostEcho(ctx context.Context) (ImplResponse, error) {
	// TODO - update PostEcho with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.

	// TODO: Uncomment the next line to return response Response(200, PostEcho200Response{}) or use other options such as http.Ok ...
	// return Response(200, PostEcho200Response{}), nil

	// TODO: Uncomment the next line to return response Response(4XX, {}) or use other options such as http.Ok ...
	// return Response(4XX, nil),nil

	// TODO: Uncomment the next line to return response Response(5XX, {}) or use other options such as http.Ok ...
	// return Response(5XX, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("PostEcho method not implemented")
}

// GetHello - Get a hello message
func (s *DefaultAPIService) GetHello(ctx context.Context) (ImplResponse, error) {
	// TODO - update GetHello with the required logic for this service method.
	// Add api_default_service.go to the .openapi-generator-ignore to avoid overwriting this service implementation when updating open api generation.
	fmt.Println("Hello from the say hello function")
	// TODO: Uncomment the next line to return response Response(200, GetHello200Response{}) or use other options such as http.Ok ...
	response := GetHelloResponse()
	return Response(200, response), nil

	// TODO: Uncomment the next line to return response Response(4XX, {}) or use other options such as http.Ok ...
	// return Response(4XX, nil),nil

	// TODO: Uncomment the next line to return response Response(5XX, {}) or use other options such as http.Ok ...
	// return Response(5XX, nil),nil

	return Response(http.StatusNotImplemented, nil), errors.New("GetHello method not implemented")
}
