// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Simple API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package simple_api




type PostEcho200Response struct {

	EchoedMessage string `json:"echoedMessage"`
}

// AssertPostEcho200ResponseRequired checks if the required fields are not zero-ed
func AssertPostEcho200ResponseRequired(obj PostEcho200Response) error {
	elements := map[string]interface{}{
		"echoedMessage": obj.EchoedMessage,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertPostEcho200ResponseConstraints checks if the values respects the defined constraints
func AssertPostEcho200ResponseConstraints(obj PostEcho200Response) error {
	return nil
}
