// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * Simple API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * API version: 1.0.0
 */

package simple_api




type ErrorMessage struct {

	Error string `json:"error"`
}

// AssertErrorMessageRequired checks if the required fields are not zero-ed
func AssertErrorMessageRequired(obj ErrorMessage) error {
	elements := map[string]interface{}{
		"error": obj.Error,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertErrorMessageConstraints checks if the values respects the defined constraints
func AssertErrorMessageConstraints(obj ErrorMessage) error {
	return nil
}
